CherryCreekSystems.Website/Models/QuotesViewModel.cs
using CherryCreekSystems.Domain;
using PagedList;
using System.Collections.Generic;
using System.Web.Mvc;

namespace CherryCreekSystems.Website.Models
{
    public class QuotesViewModel
    {
        public QuotesViewModel()
        {
            Page = 1;
            QuoteStatusId = 1;
        }

        public int? QuoteId { get; set; }
        public int Page { get; set; }

        public int? DistributorId { get; set; }
        public IList<SelectListItem> Distributors { get; set; }

        public int? CustomerId { get; set; }
        public IList<SelectListItem> Customers { get; set; }

        public int? SalesRepId { get; set; }
        public IList<SelectListItem> SalesReps { get; set; }

        public int? QuoteStatusId { get; set; }
        public IList<SelectListItem> QuoteStatuses { get; set; }

        public int? BoomTypeId { get; set; }
        public IList<SelectListItem> BoomTypes { get; set; }

        public IPagedList<QuoteViewModel> QuoteRequests { get; set; }
    }

    public class QuoteViewModel
    {
        public QuoteRequest QuoteRequest { get; set; }

        public IEnumerable<string> BoomTypes { get; set; }
    }
}

CherryCreekSystems.Website/Areas/Administrator/Controllers/QuoteController.cs
using CherryCreekSystems.BL;
using CherryCreekSystems.BL.QueryExtensions;
using CherryCreekSystems.BL.Utils;
using CherryCreekSystems.DAL;
using CherryCreekSystems.Domain;
using CherryCreekSystems.Domain.ViewModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace CherryCreekSystems.Website.Areas.Administrator.Controllers
{
    public class QuoteController : Controller
    {
        //FOR WEB SERVICE TO SUITE CRM
        public async Task<JsonResult> Quote()
        {
            var quote = await (new QuoteRequestService().Get().ByQuoteId(1));

            var quoteViewModel = new QuoteViewModel()
            {
                Systems = quote.QuoteBoomSystemsData.QuoteBoomSystems,
                SelectedBoomType = 1,
                QuoteId = 0,
                QuoteNumber = "111111111",
                QuoteTotal = 100.55,
                SelectedQuoteStatusId = 1,
                SelectedCustomerId = 1,
                SelectedDistributorId = 5,
                SelectedSalesRepId = 4,
                ShipAddress = "a test address",
                LeadTime = 7,
                PurchaseOrder = "an order",
                Discount = "1,333",
                PriceLevel = 22.7,
                SelectedGreenhouseTypeId = 5,
                NumberOfBays = 6,
                BayLength = 200,
                BayWidth = 100,
                HoseSize = 12.34,
                GrowingSurfaceHeight = 33.55,
                PostSpacing = 77,
                PostDimensions = "300 X 400",
                FreightEstimate = "111",
                InstallationEstimate = "222",
                SteelEstimate = "333",
                OrderDate = DateTime.Now.ToString("MM/dd/yyyy"),
                DueDate = DateTime.Now.AddDays(30).ToString("MM/dd/yyyy"),
                SprayBarSize = 88,
                NumberOfBaySidewalls = 5,
                BottomCordType = "RD",
                BottomCordHeight = 5.5,
                BottomCordSize = "7 X 8",
                Location = "my house",
                AdditionalInformation = "some additional info",
                CustomerNotes = "another notes",
                TrussSpacing = 1.2,
                WalkwayWidth = 3.4,
                ClearanceWidth = 4.5,

                QuantityOfSystems = 4,
                SelectedDrumSize = 20,
                BasketSpacing = 1.2,
                SelectedControllerType = "Standard Enhanced",
                SelectedNumberOfLayers = 3,
                CenterBayWaterStation = false,
                EvVpdThirdPartyControl = false,
                ThreeFourthAMIADFilterAssembly = false,
                LockLine = false,
                ExtensionHangerLength = 5.5,
                SelectedPulleyBracketSpacing = 5,
                RemotePullChainSwitch = false,
                DRAMMRedheadBreakerUpgrade = false,
                WaterSolenoidControl = false,
                SelectedFeed = "Center Feed",
                Customer = new CustomerViewModel { CompanyName = "Test Company", ContactName = "Francisco Ramos" }
            };

            return Json(quoteViewModel, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Index()
        {
            var quoteCreationViewModel = new QuoteCreationViewModel();
            return View(quoteCreationViewModel);
        }

        public async Task<ContentResult> Save(QuoteCreationViewModel viewModel)
        {
            var quoteRequest = new QuoteRequest
            {
                ContactName = viewModel.Customer.ContactName,
                Phone = viewModel.Customer.Phone,
                Fax = viewModel.Customer.Fax,
                Email = viewModel.Customer.Email,
                FullAddress = viewModel.FullAddress,
                CustomerId = viewModel.SelectedCustomerId,
                ShipAddressId = viewModel.SelectedShipAddressId,
                SalesRepId = viewModel.SelectedSalesRepId,
                DistributorId = viewModel.SelectedDistributorId,
                LeadTime = viewModel.LeadTime.ToSafeString(),
                SteelEstimate = viewModel.SteelEstimate,
                FreightEstimate = viewModel.FreightEstimate,
                InstallationEstimate = viewModel.InstallationEstimate,
                Discount = viewModel.Discount,
                PriceLevel = viewModel.PriceLevel.ToSafeDouble(),
                PurchaseOrder = viewModel.PurchaseOrder,
                OrderDate = viewModel.OrderDate.ToSafeDate(),
                DueDate = viewModel.DueDate.ToSafeDate(),
                Active = true
            };

            //Check if status changed
            if (viewModel.SelectedQuoteStatusId != quoteRequest.QuoteStatusId)
            {
                quoteRequest.StatusDate = DateTime.Now;
            }

            var containsRevisionNumber = viewModel.QuoteNumber.ToSafeString().EndsWith("-" + quoteRequest.Revision);
            var quoteNumber = viewModel.QuoteNumber;
            if (containsRevisionNumber)
            {
                var dashIndex = quoteNumber.LastIndexOf("-");
                quoteNumber = quoteNumber.Substring(0, dashIndex);
            }

            //Update to new status
            quoteRequest.QuoteStatusId = viewModel.SelectedQuoteStatusId;
            quoteRequest.Revision++;

            quoteRequest.QuoteNumber = viewModel.QuoteNumber;

            var boom = new Boom
            {
                //Greenhouse values
                AdditionalInformation = viewModel.AdditionalInformation,
                CustomerNote = viewModel.CustomerNotes,
                GreenHouseTypeId = viewModel.SelectedGreenhouseTypeId,
                NumberOfBays = viewModel.NumberOfBays.ToSafeInt(),
                BayLengthInFeet = viewModel.BayLength.ToSafeDouble(),
                BayWidthInFeet = viewModel.BayWidth.ToSafeDouble(),
                NumberOfBaySideWalls = viewModel.NumberOfBaySidewalls.ToSafeInt(),
                WalkwayWidthInInches = viewModel.WalkwayWidth.ToSafeDouble(),
                ClearanceWidthInInches = viewModel.ClearanceWidth.ToSafeDouble(),
                BottomCordHeightInFeet = viewModel.BottomCordHeight.ToSafeDouble(),
                TrussSpacingInFeet = viewModel.TrussSpacing.ToSafeDouble(),
                BottomCordType = viewModel.BottomCordType,
                BottomCordSize = viewModel.BottomCordSize,
                GrowingSurfaceHeightInInches = viewModel.GrowingSurfaceHeight.ToSafeDouble(),
                PostSpacingInFeet = viewModel.PostSpacing.ToSafeDouble(),
                PostDimensionsInInchesSquared = viewModel.PostDimensions,
                SprayBarSize = viewModel.SprayBarSize.ToSafeDouble(),
                HoseSize = viewModel.HoseSize.ToSafeDouble(),
                Location = viewModel.Location
            };

            //Echo System values
            boom.BoomTypeId = viewModel.SelectedBoomType;
            boom.QuantityOfSystems = viewModel.QuantityOfSystems.ToSafeInt();
            boom.DrumSize = viewModel.SelectedDrumSize.ToSafeInt();
            boom.BasketSpacing = viewModel.BasketSpacing.ToSafeDouble();
            boom.ControllerType = viewModel.SelectedControllerType;
            boom.NumberOfLayers = viewModel.SelectedNumberOfLayers.ToSafeInt();
            boom.Feed = viewModel.SelectedFeed;

            boom.EvVpd = viewModel.EvVpdThirdPartyControl;
            boom.CenterBayWaterStationRequested = viewModel.CenterBayWaterStation;
            boom.AMIADFilterAssemblyRequested = viewModel.ThreeFourthAMIADFilterAssembly;
            boom.LocklineRequested = viewModel.LockLine;

            boom.ExtensionHangerLengthInInches = viewModel.ExtensionHangerLength.ToSafeDouble();
            boom.PulleyBracketSpacingInFeet = viewModel.SelectedPulleyBracketSpacing.ToSafeDouble();
            boom.RemotePullChainSwitchRequested = viewModel.RemotePullChainSwitch;
            boom.DRAMMRedheadBreakerUpgradeRequested = viewModel.DRAMMRedheadBreakerUpgrade;
            boom.WaterSolenoidControlRequested = viewModel.WaterSolenoidControl;

            var context = new DataContext();
            var quoteRequestService = new QuoteRequestService(context);
            var quoteBoomSystemService = new QuoteBoomSystemService(context);

            quoteRequestService.Add(quoteRequest);
            await context.SaveChangesAsync();

            var quoteSystemResult = await quoteBoomSystemService.CreateQuoteBoomSystem(quoteRequest, boom);
            quoteRequest.QuoteNumber = await quoteRequestService.CreateQuoteNumber(quoteRequest);
            await context.SaveChangesAsync();

            var responseViewModel = new QuoteCreationResponseViewModel();
            responseViewModel.QuoteNumber = quoteRequest.QuoteNumber;
            if (quoteSystemResult.CalculationErrors.Any())
            {
                responseViewModel.CalculationErrors = quoteSystemResult.CalculationErrors;
            }

            var jsonResponse = JsonConvert.SerializeObject(responseViewModel);
            return Content(jsonResponse);
        }

        public async Task<ContentResult> GetQuoteViewModel(int? quoteId)
        {
            var specsService = new SpecService();
            var statusService = new QuoteStatusService();
            var distributorsService = new DistributorService();
            var customersService = new CustomerService();
            var salesRepService = new SalesRepService();
            var greenhouseService = new GreenhouseTypeService();

            var specsQuery = specsService.Get().WithSpecLookups().ToListAsync();
            var statusesQuery = statusService.Get().OrderedById().ToListAsync();
            var distributorsQuery = distributorsService.Get().OrderedByName().ToListAsync();
            var salesRepsQuery = salesRepService.Get().OrderedByName().ToListAsync();

CherryCreekSystems.Website/Areas/Administrator/Controllers/QuotesController.cs
using System;
using CherryCreekSystems.DAL;
using CherryCreekSystems.Website.Models;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using CherryCreekSystems.BL;
using CherryCreekSystems.BL.QueryExtensions;
using CherryCreekSystems.Domain;
using Newtonsoft.Json;

namespace CherryCreekSystems.Website.Areas.Administrator.Controllers
{
    [Authorize(Roles = "administrator")]
    public class QuotesController : Website.Controllers.QuotesController
    {
        public async Task<ActionResult> Index(QuotesViewModel viewModel)
        {
            var distributorService = new DistributorService();
            var customerService = new CustomerService();
            var salesRepService = new SalesRepService();
            var quoteStatusService = new QuoteStatusService();

            var getDistributorsTask = distributorService.Get().OrderedByName().ToListAsync();
            var getCustomersTask = customerService.Get().OrderedByCompanyName().ToListAsync();
            var getSalesRepsTask = salesRepService.Get().OrderedByName().ToListAsync();
            var getQuoteStatusesTask = quoteStatusService.Get().OrderedByName().ToListAsync();

            viewModel.QuoteRequests = await GetQuoteRequestsPage(
                viewModel.Page,
                distributorId: viewModel.DistributorId,
                customerId: viewModel.CustomerId,
                salesRepId: viewModel.SalesRepId,
                quoteStatusId: viewModel.QuoteStatusId,
                boomTypeId: viewModel.BoomTypeId);

            var boomTypeIds = BoomTypeStructure.GetList();
            var distributors = await getDistributorsTask;
            var customers = await getCustomersTask;
            var salesReps = await getSalesRepsTask;
            var quoteStatuses = await getQuoteStatusesTask;

            viewModel.Distributors = distributors.Select(d => new SelectListItem
            {
                Value = d.Id.ToString(),
                Text = d.Name
            }).ToList();

            viewModel.Distributors.Insert(0, new SelectListItem { Value = "", Text = "All" });

            viewModel.Customers = customers.Select(d => new SelectListItem
            {
                Value = d.Id.ToString(),
                Text = d.CompanyName
            }).ToList();

            viewModel.Customers.Insert(0, new SelectListItem { Value = "", Text = "All" });

            viewModel.SalesReps = salesReps.Select(d => new SelectListItem
            {
                Value = d.Id.ToString(),
                Text = d.Name
            }).ToList();

            viewModel.SalesReps.Insert(0, new SelectListItem { Value = "", Text = "All" });

            viewModel.QuoteStatuses = quoteStatuses.Select(d => new SelectListItem
            {
                Value = d.Id.ToString(),
                Text = d.Name
            }).ToList();

            viewModel.QuoteStatuses.Insert(0, new SelectListItem { Value = "", Text = "All" });

            viewModel.BoomTypes = boomTypeIds.Select(d => new SelectListItem
            {
                Value = d.Id.ToString(),
                Text = d.Name
            }).ToList();

            viewModel.BoomTypes.Insert(0, new SelectListItem { Value = "", Text = "All" });

            return View(viewModel);
        }
    }
}

CherryCreekSystems.Website/Areas/Customer/Controllers/QuotesController.cs
using System;
using System.Collections.Generic;
using CherryCreekSystems.DAL;
using CherryCreekSystems.Website.Models;
using Microsoft.AspNet.Identity;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using CherryCreekSystems.BL;
using CherryCreekSystems.BL.QueryExtensions;
using CherryCreekSystems.Domain;
using Newtonsoft.Json;
using PagedList;

namespace CherryCreekSystems.Website.Areas.Customers.Controllers
{
    [Authorize(Roles = "customer")]
    public class QuotesController : Website.Controllers.QuotesController
    {
        public async Task<ActionResult> Index(QuotesViewModel viewModel)
        {
            var quoteStatusService = new QuoteStatusService();
            var getQuoteStatusesTask = quoteStatusService.Get().OrderedByName().ToListAsync();

            ApplicationUser user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            viewModel.CustomerId = (await user.CustomerIds()).First();

            if (viewModel.QuoteId.HasValue)
            {
                QuoteRequestService quoteRequestService = new QuoteRequestService();
                var singleQuote = await quoteRequestService.Get().ByQuoteId(viewModel.QuoteId.Value);
                var singleQuoteViewModel = new QuoteViewModel
                {
                    QuoteRequest = singleQuote,
                    BoomTypes = singleQuote.GetBoomTypes()
                };
                var allowedToSeeInfo = await SecurityCheck(user, singleQuote);
                if (!allowedToSeeInfo)
                {
                    return HttpNotFound();
                }
                viewModel.QuoteRequests = new PagedList<QuoteViewModel>(new List<QuoteViewModel> { singleQuoteViewModel }, 1, 1);
            }
            else
            {
                viewModel.QuoteRequests = await GetQuoteRequestsPage(
                        viewModel.Page,
                        customerId: viewModel.CustomerId,
                        quoteStatusId: viewModel.QuoteStatusId,
                        boomTypeId: viewModel.BoomTypeId);
            }

            var boomTypeIds = BoomTypeStructure.GetList();
            var quoteStatuses = await getQuoteStatusesTask;

            viewModel.QuoteStatuses = quoteStatuses.Select(d => new SelectListItem
            {
                Value = d.Id.ToString(),
                Text = d.Name
            }).ToList();

            viewModel.QuoteStatuses.Insert(0, new SelectListItem { Value = "", Text = "All" });

            viewModel.BoomTypes = boomTypeIds.Select(d => new SelectListItem
            {
                Value = d.Id.ToString(),
                Text = d.Name
            }).ToList();

            viewModel.BoomTypes.Insert(0, new SelectListItem { Value = "", Text = "All" });

            return View(viewModel);
        }
    }
}

CherryCreekSystems.Website/Areas/SalesRep/Views/Quotes/Index.cshtml
@model CherryCreekSystems.Website.Models.QuotesViewModel

@{
    ViewBag.Title = "Index";
}

@using (Ajax.BeginForm("QuotesPage", "Quotes", null, new AjaxOptions
{
    HttpMethod = "POST",
    InsertionMode = InsertionMode.ReplaceWith,
    UpdateTargetId = "QuotesTable",
    OnBegin = "toggleLoading",
    OnComplete = "toggleLoading"
}, new { @role = "form" }))
{
    @*@Html.AntiForgeryToken()*@

    <div class="form-horizontal">
        <h3>Search Quotes</h3>
        <hr />
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    @Html.Label("Customer: ", htmlAttributes: new { @class = "control-label col-md-5" })
                    <div class="col-md-7">
                        @Html.DropDownListFor(model => model.CustomerId, Model.Customers, htmlAttributes: new { @class = "form-control AjaxSubmitForm" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("Status: ", htmlAttributes: new { @class = "control-label col-md-5" })
                    <div class="col-md-7">
                        @Html.DropDownListFor(model => model.QuoteStatusId, Model.QuoteStatuses, htmlAttributes: new { @class = "form-control AjaxSubmitForm" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("Boom Type: ", htmlAttributes: new { @class = "control-label col-md-5" })
                    <div class="col-md-7">
                        @Html.DropDownListFor(model => model.BoomTypeId, Model.BoomTypes, htmlAttributes: new { @class = "form-control AjaxSubmitForm" })
                    </div>
                </div>
            </div>
            <div class="col-md-push-2 col-md-4">
                <div class="row">
                    <div class="col-md-12" style="text-align: center">
                        <img src="~/Content/images/cc_logo.gif" alt="logo" height="115" width="95" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        For any questions about your quotes, contact us at:
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">

                        <b>Email</b>
                    </div>
                    <div class="col-md-9">
                        <a href="mailto:walter@cherrycreeksystems.com">walter@cherrycreeksystems.com</a>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-3">
                        <b>Web</b>
                    </div>
                    <div class="col-md-9">
                        <a href="http://www.cherrycreeksystems.com" target="_blank">www.cherrycreeksystems.com</a>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-3">
                        <b>Direct</b>
                    </div>
                    <div class="col-md-9">
                        (719) 637-2035
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-3">
                        <b>Phone</b>
                    </div>
                    <div class="col-md-9">
                        (719) 380-8373
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-3">
                        <b>Toll Free</b>
                    </div>
                    <div class="col-md-9">
                        (877) 558-3246
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@Html.Partial("_Quotes", Model)

@section scripts{

    <script src="~/Scripts/AjaxUtilities.js"></script>
}

CherryCreekSystems.Website/Areas/SalesRep/Views/Quotes/Systems.cshtml
@model CherryCreekSystems.Website.Models.QuoteBoomSystemsViewModel

@Html.Partial("_NavigateBackToQuotesPage", Model)

<div class="row form-group" style="margin-top: 50px">
    <div class="col-sm-2">
        <h4 class="control-label">Quote #:</h4>
    </div>
    <div class="col-sm-10">
        <h4 class="control-label">@Model.QuoteNumber</h4>
    </div>
</div>
<div class="row">
    <div class="col-sm-2">
        <h4 class="control-label">Expected Ship Date:</h4>
    </div>
    <div class="col-sm-10">
        <h4 class="control-label"> @Model.ShippingDate</h4>
    </div>
</div>

@Html.Partial("_QuoteSystems", Model)

@section scripts
{
    <script src="~/Scripts/kendo.all.min.js"></script>

    <script>
        $(document).ready(function () {

            var statusCharts = $(".statusChart");
            statusCharts.each(function() {

                var chart = $(this);
                var statusData = chart.data("status");

                chart.kendoChart({
                    dataSource: {
                        data: statusData
                    },
                    title: {
                        text: "Manufacturing Progress"
                    },
                    series: [{
                        field: "value",
                        type: "bar",
                        colorField: "userColor"
                    }],
                    valueAxis: {
                        min: 0,
                        max: 100
                    },
                    categoryAxis: {
                        categories: ["Customer Information", "Engineering", "Production", "Galvanizer", "Assembly", "Shipping"]
                    },
                    tooltip: {
                    visible: true,
                    template: "${value}"
                }
                });
            });
        });
    </script>
}