CherryCreekSystems.Website/Models/DistributorsViewModel.cs
using CherryCreekSystems.Domain;
using PagedList;

namespace CherryCreekSystems.Website.Models
{
    public class DistributorsViewModel
    {
        public DistributorsViewModel()
        {
            Page = 1;
        }

        public int Page { get; set; }

        public string Search { get; set; }

        public IPagedList<DistributorUser> Distributors { get; set; }
    }
}

CherryCreekSystems.Website/Areas/Administrator/Controllers/DistributorsController.cs
using CherryCreekSystems.DAL;
using CherryCreekSystems.Domain;
using CherryCreekSystems.Website.Models;
using PagedList;
using PagedList.EntityFramework;
using System.Threading.Tasks;
using System.Web.Mvc;
using CherryCreekSystems.BL.QueryExtensions;

namespace CherryCreekSystems.Website.Areas.Administrator.Controllers
{
    [Authorize(Roles = "administrator")]
    public class DistributorsController : Controller
    {
        // GET: Administrator/Distributors
        public async Task<ActionResult> Index(DistributorsViewModel viewModel)
        {
            viewModel.Distributors = await GetDistributorsPage(viewModel.Page, viewModel.Search);

            return View(viewModel);
        }

        public async Task<ActionResult> DistributorsPage(DistributorsViewModel viewModel)
        {
            viewModel.Distributors = await GetDistributorsPage(viewModel.Page, viewModel.Search);

            return PartialView("_Distributors", viewModel);
        }

        public static async Task<IPagedList<DistributorUser>> GetDistributorsPage(
                  int page,
                  string searchTerm)
        {
            using (var context = new DataContext())
            {
                var distributors = context.GetDistributorUsers()
                                          .BySearch(searchTerm)
                                          .GetOrdered();

                return await distributors.ToPagedListAsync(page, 15);
            }
        }
    }
}

CherryCreekSystems.Website/Areas/Distributor/Controllers/QuotesController.cs
using CherryCreekSystems.DAL;
using CherryCreekSystems.Domain;
using CherryCreekSystems.Website.Models;
using Microsoft.AspNet.Identity;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using CherryCreekSystems.BL;
using CherryCreekSystems.BL.QueryExtensions;

namespace CherryCreekSystems.Website.Areas.Distributors.Controllers
{
    [Authorize(Roles = "distributor")]
    public class QuotesController : Website.Controllers.QuotesController
    {
        // GET: Administrator/Quotes
        public async Task<ActionResult> Index(QuotesViewModel viewModel)
        {
            var customerService = new CustomerService();
            var quoteStatusService = new QuoteStatusService();

            var getQuoteStatusesTask = quoteStatusService.Get().OrderedByName().ToListAsync();

            ApplicationUser user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            viewModel.DistributorId = (await user.DistributorIds()).First();

            var getCustomersTask = customerService.GetCustomersForDistributor(viewModel.DistributorId.Value).ToListAsync();

            viewModel.QuoteRequests = await GetQuoteRequestsPage(
                viewModel.Page,
                distributorId: viewModel.DistributorId,
                customerId: viewModel.CustomerId,
                quoteStatusId: viewModel.QuoteStatusId,
                boomTypeId: viewModel.BoomTypeId);

            var boomTypeIds = BoomTypeStructure.GetList();
            var quoteStatuses = await getQuoteStatusesTask;
            var customers = await getCustomersTask;

            viewModel.Customers = customers.Select(d => new SelectListItem
            {
                Value = d.Id.ToString(),
                Text = d.CompanyName
            }).ToList();

            viewModel.Customers.Insert(0, new SelectListItem { Value = "", Text = "All" });

            viewModel.QuoteStatuses = quoteStatuses.Select(d => new SelectListItem
            {
                Value = d.Id.ToString(),
                Text = d.Name
            }).ToList();

            viewModel.QuoteStatuses.Insert(0, new SelectListItem { Value = "", Text = "All" });

            viewModel.BoomTypes = boomTypeIds.Select(d => new SelectListItem
            {
                Value = d.Id.ToString(),
                Text = d.Name
            }).ToList();

            viewModel.BoomTypes.Insert(0, new SelectListItem { Value = "", Text = "All" });

            return View(viewModel);
        }
    }
}

CherryCreekSystems.Website/Areas/Administrator/Views/Distributors/Index.cshtml
@model CherryCreekSystems.Website.Models.DistributorsViewModel

@using (Ajax.BeginForm("DistributorsPage", "Distributors", null, new AjaxOptions
{
    HttpMethod = "POST",
    InsertionMode = InsertionMode.ReplaceWith,
    UpdateTargetId = "DistributorsTable",
    OnBegin = "toggleLoading",
    OnComplete = "toggleLoading"
}, new { @role = "form" }))
{
    @*@Html.AntiForgeryToken()*@

    <div class="form-horizontal">
        <h3>Distributors</h3>
        <hr />

        <div class="form-group" style="margin-top: 20px">
            <div class="form-group">
                <label for="SearchTerm" class="control-label col-sm-3 text-right">Search: </label>
                <div class="col-sm-3">
                    <input type="text" name="Search" id="SearchTerm" class="form-control" />
                </div>
                <div class="col-sm-1">
                    <input type="submit" value="Find" class="btn btn-default btn-primary" />
                </div>
            </div>
        </div>
    </div>
}

<div style="margin-top: 50px">
    @Html.Partial("_Distributors", Model)
</div>

@section scripts{

    <script src="~/Scripts/AjaxUtilities.js"></script>
}