CherryCreekSystems.Website/Models/SalesRepsViewModel.cs
using CherryCreekSystems.Domain;
using PagedList;

namespace CherryCreekSystems.Website.Models
{
    public class SalesRepsViewModel
    {
        public SalesRepsViewModel()
        {
            Page = 1;
        }

        public int Page { get; set; }

        public string Search { get; set; }

        public IPagedList<SalesRepUser> SalesReps { get; set; }
    }
}

CherryCreekSystems.Website/Areas/Administrator/Controllers/SalesRepsController.cs
using CherryCreekSystems.DAL;
using CherryCreekSystems.Domain;
using CherryCreekSystems.Website.Models;
using PagedList;
using PagedList.EntityFramework;
using System.Threading.Tasks;
using System.Web.Mvc;
using CherryCreekSystems.BL.QueryExtensions;

namespace CherryCreekSystems.Website.Areas.Administrator.Controllers
{
    [Authorize(Roles = "administrator")]
    public class SalesRepsController : Controller
    {
        public async Task<ActionResult> Index(SalesRepsViewModel viewModel)
        {
            viewModel.SalesReps = await GetSalesRepsPage(viewModel.Page, viewModel.Search);

            return View(viewModel);
        }

        public async Task<ActionResult> SalesRepsPage(SalesRepsViewModel viewModel)
        {
            viewModel.SalesReps = await GetSalesRepsPage(viewModel.Page, viewModel.Search);

            return PartialView("_SalesReps", viewModel);
        }

        public static async Task<IPagedList<SalesRepUser>> GetSalesRepsPage(
                  int page,
                  string searchTerm)
        {
            using (var context = new DataContext())
            {
                var salesReps = context.GetSalesRepUsers()
                                          .BySearch(searchTerm)
                                          .GetOrdered();

                return await salesReps.ToPagedListAsync(page, 15);
            }
        }
    }
}

CherryCreekSystems.Website/Areas/SalesRep/Controllers/QuotesController.cs
using CherryCreekSystems.DAL;
using CherryCreekSystems.Website.Models;
using Microsoft.AspNet.Identity;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using CherryCreekSystems.BL;
using CherryCreekSystems.BL.QueryExtensions;
using CherryCreekSystems.Domain;

namespace CherryCreekSystems.Website.Areas.SalesReps.Controllers
{
    [Authorize(Roles = "salesrep")]
    public class QuotesController : Website.Controllers.QuotesController
    {
        public async Task<ActionResult> Index(QuotesViewModel viewModel)
        {
            var customerService = new CustomerService();
            var quoteStatusService = new QuoteStatusService();

            var getQuoteStatusesTask = quoteStatusService.Get().OrderedByName().ToListAsync();

            ApplicationUser user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            viewModel.SalesRepId = (await user.SalesRepIds()).First();

            var getCustomersTask = customerService.GetCustomersForSalesRep(viewModel.SalesRepId.Value).ToListAsync();

            viewModel.QuoteRequests = await GetQuoteRequestsPage(
                viewModel.Page,
                customerId: viewModel.CustomerId,
                salesRepId: viewModel.SalesRepId,
                quoteStatusId: viewModel.QuoteStatusId,
                boomTypeId: viewModel.BoomTypeId);

            var boomTypeIds = BoomTypeStructure.GetList();
            var quoteStatuses = await getQuoteStatusesTask;
            var customers = await getCustomersTask;

            viewModel.Customers = customers.Select(d => new SelectListItem
            {
                Value = d.Id.ToString(),
                Text = d.CompanyName
            }).ToList();

            viewModel.Customers.Insert(0, new SelectListItem { Value = "", Text = "All" });

            viewModel.QuoteStatuses = quoteStatuses.Select(d => new SelectListItem
            {
                Value = d.Id.ToString(),
                Text = d.Name
            }).ToList();

            viewModel.QuoteStatuses.Insert(0, new SelectListItem { Value = "", Text = "All" });

            viewModel.BoomTypes = boomTypeIds.Select(d => new SelectListItem
            {
                Value = d.Id.ToString(),
                Text = d.Name
            }).ToList();

            viewModel.BoomTypes.Insert(0, new SelectListItem { Value = "", Text = "All" });

            return View(viewModel);
        }
    }
}

CherryCreekSystems.Website/Areas/Administrator/Views/SalesReps/Index.cshtml
@model CherryCreekSystems.Website.Models.SalesRepsViewModel

@using (Ajax.BeginForm("SalesRepsPage", "SalesReps", null, new AjaxOptions
{
    HttpMethod = "POST",
    InsertionMode = InsertionMode.ReplaceWith,
    UpdateTargetId = "SalesRepsTable",
    OnBegin = "toggleLoading",
    OnComplete = "toggleLoading"
}, new { @role = "form" }))
{
    @*@Html.AntiForgeryToken()*@

    <div class="form-horizontal">
        <h3>Sales Reps</h3>
        <hr />

        <div class="form-group" style="margin-top: 20px">
            <div class="form-group">
                <label for="SearchTerm" class="control-label col-sm-3 text-right">Search: </label>
                <div class="col-sm-3">
                    <input type="text" name="Search" id="SearchTerm" class="form-control" />
                </div>
                <div class="col-sm-1">
                    <input type="submit" value="Find" class="btn btn-default btn-primary" />
                </div>
            </div>
        </div>
    </div>
}

<div style="margin-top: 50px">
    @Html.Partial("_SalesReps", Model)
</div>

@section scripts{

    <script src="~/Scripts/AjaxUtilities.js"></script>
}